// --------------------------------------------------------------------------------------------------------------------
// <copyright file="GenerateKeyForm.Designer.cs" company="Florian Amstutz">
//   Copyright (c) Florian Amstutz. All rights reserved.
// </copyright>
// <auto-generated />
// --------------------------------------------------------------------------------------------------------------------

namespace YAEM.TestClient
{
    partial class GenerateKeyForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.RandomKeyLabel = new System.Windows.Forms.Label();
            this.KeyTextBox = new System.Windows.Forms.TextBox();
            this.UseKeyButton = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // RandomKeyLabel
            // 
            this.RandomKeyLabel.AutoSize = true;
            this.RandomKeyLabel.Location = new System.Drawing.Point(12, 9);
            this.RandomKeyLabel.Name = "RandomKeyLabel";
            this.RandomKeyLabel.Size = new System.Drawing.Size(68, 13);
            this.RandomKeyLabel.TabIndex = 0;
            this.RandomKeyLabel.Text = "Random Key";
            // 
            // KeyTextBox
            // 
            this.KeyTextBox.Location = new System.Drawing.Point(86, 6);
            this.KeyTextBox.Name = "KeyTextBox";
            this.KeyTextBox.Size = new System.Drawing.Size(111, 20);
            this.KeyTextBox.TabIndex = 1;
            this.KeyTextBox.TextChanged += new System.EventHandler(this.KeyTextBoxTextChanged);
            // 
            // UseKeyButton
            // 
            this.UseKeyButton.Location = new System.Drawing.Point(203, 4);
            this.UseKeyButton.Name = "UseKeyButton";
            this.UseKeyButton.Size = new System.Drawing.Size(75, 23);
            this.UseKeyButton.TabIndex = 2;
            this.UseKeyButton.Text = "Use Key";
            this.UseKeyButton.UseVisualStyleBackColor = true;
            this.UseKeyButton.Click += new System.EventHandler(this.UseKeyButtonClick);
            // 
            // GenerateKeyForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(287, 31);
            this.Controls.Add(this.UseKeyButton);
            this.Controls.Add(this.KeyTextBox);
            this.Controls.Add(this.RandomKeyLabel);
            this.Name = "GenerateKeyForm";
            this.Text = "GenerateKeyForm";
            this.Load += new System.EventHandler(this.GenerateKeyFormLoad);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label RandomKeyLabel;
        private System.Windows.Forms.TextBox KeyTextBox;
        private System.Windows.Forms.Button UseKeyButton;
    }
}